import type { ThemeConfig } from "../schema/theme-config.schema";
import { downloadFile } from "./css";

// Convert oklch() CSS string to a Tailwind-safe value
function toTailwindValue(oklchStr: string): string {
    // Tailwind 3 uses HSL, Tailwind 4 supports oklch natively
    // We output oklch since the project uses Tailwind 4
    return oklchStr;
}

export function exportAsTailwind(config: ThemeConfig): string {
    const t = config.tokens;

    return `// tailwind.config.ts
// Generated by AI Design Engineer
// Add this to your tailwind.config.ts extend block

import type { Config } from "tailwindcss";

const config: Config = {
  theme: {
    extend: {
      colors: {
        background:  "var(--background)",
        foreground:  "var(--foreground)",
        primary: {
          DEFAULT:    "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT:    "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        muted: {
          DEFAULT:    "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT:    "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        destructive: {
          DEFAULT:    "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        card: {
          DEFAULT:    "var(--card)",
          foreground: "var(--card-foreground)",
        },
        popover: {
          DEFAULT:    "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        border:  "var(--border)",
        input:   "var(--input)",
        ring:    "var(--ring)",
      },
      borderRadius: {
        sm:  "calc(var(--radius) - 4px)",
        md:  "var(--radius)",
        lg:  "calc(var(--radius) + 2px)",
        xl:  "calc(var(--radius) + 4px)",
        "2xl": "calc(var(--radius) + 8px)",
      },
    },
  },
};

export default config;

/* 
 * Theme: ${config.primaryHex} · ${config.harmonyType} · ${config.ideologyId}
 * Generated: ${new Date().toLocaleDateString()}
 * 
 * Also add this to your globals.css:
 *
${exportCSSComment(config)}
 */`;
}

function exportCSSComment(config: ThemeConfig): string {
    const t = config.tokens;
    return ` * :root {
 *   --background: ${t.background};
 *   --foreground: ${t.foreground};
 *   --primary: ${t.primary};
 *   --primary-foreground: ${t.primaryForeground};
 *   --secondary: ${t.secondary};
 *   --secondary-foreground: ${t.secondaryForeground};
 *   --muted: ${t.muted};
 *   --muted-foreground: ${t.mutedForeground};
 *   --accent: ${t.accent};
 *   --accent-foreground: ${t.accentForeground};
 *   --destructive: ${t.destructive};
 *   --destructive-foreground: ${t.destructiveForeground};
 *   --border: ${t.border};
 *   --input: ${t.input};
 *   --ring: ${t.ring};
 *   --radius: ${t.radius};
 *   --card: ${t.card};
 *   --card-foreground: ${t.cardForeground};
 * }`;
}

export function downloadTailwind(config: ThemeConfig): void {
    const content = exportAsTailwind(config);
    downloadFile(content, "tailwind.theme.ts", "text/plain");
}